### ISSUE TITLE
Order of Input Parameters from file in PreOpt directory

### ISSUE THREAD

**Issue by PaschalisEconomou** [zhoutl1106/zerasure#1]
In the README, it says that data in the file "PreOpt/ge_100_03_06_01_1000_weighted_s13.txt" is read in the order (K, M, W, X, Y). 

However, judging by your source code (for example, zcauchy.cpp: line 21) it seems like it is being read in as (K, M, W, Y, X).

Is that correct?

**Comment by zhoutl1106** [comment]
Hi Paschali

Thank you for your interest in my repo. Yes, you're correct. I'm not that strictly follow the paper as the X and Y are only temporary variables here. It basically grabs a total of k+m numbers, uses k of them as one array (named X or Y), and rest m of them as another array (named Y or X), as the symmetric property of Cauchy matrix, it doesn't matter much.

Thank you again for pointing out that, I'll update the README accordingly.

Tianli.

________________________________
