### ISSUE TITLE
Allowable values for packetsize

### ISSUE THREAD

**Issue by PaschalisEconomou** [zhoutl1106/zerasure#2]
Hi Tianli,

Thanks for your response to my previous issue. I have another concern. The example coder does not seem to work when packetsize = 8 (running "./zerasure code 8 7" will give an output of "??? Diff" at the end). Are we allowed to have packetsize = 8? In Jerasure, the only mentioned restrictions are that packetsize should be a multiple of sizeof(long), which is 8 bytes on my computer. 

In your program, it seems like when packetsize = 8, the first parity device ends up having an exact copy of the data in the first data device. I don't know why that happens, but maybe it gives you a clue as to what the issue is. 

Regards,
Paschali

**Comment by zhoutl1106** [comment]
Hi,

That's a great question.
The default SIMD is SSE4, which is 128 bits (16 Bytes). That is also the minimum computational unit. So packetsize=8 will lead to an error.
I was setting the VEC variable in mfile to either VEC128 (means packetsize needs to be a multiple of 16B )
or VEC256(packetsize needs to be multiple of 32B ).
If you need smaller packetsize of any reason, please set the variable to neither VEC128 nor VEC256. Then it will use no-SIMD to perform long-size wise computation and that will be a minimum of 8B.
please refer to utils.cpp, line 76-121 for reference. You can even modify the last segment of fast_xor function to make it byte-wise.

Thank you.
Tianli.

________________________________

**Comment by PaschalisEconomou** [comment]
I see. Thanks for the help!

**Comment by zhoutl1106** [comment]
Hi

Could you tell me why are you interest in this repo and how will you use/integrate it in your project? Is that research, industrial or any other field?
I'm just curious and would like to know the impact of my work.

Thank you.

________________________________
